title: Avtec Location Services
author: Missy Graczyk
email: mgraczyk@avtecinc.com
description: > # this means to ignore newlines until "baseurl:"
  Location Services API Documentation site, containing all the documentation necessary...

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: cayman
